### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-http-client#116]
Would help with releases, and tracking API changes/updates.

**Comment by balupton** [comment]
So for the changelog, the approach that sander and I determined to be best is to:

1. Publish the changelog in the PR descriptions, squash the merge
2. Tag/make the release via https://github.com/textileio/js-http-client/releases by default it will get the commit description, which hopefully was the PR
3. If several PRs has merged before the release, then merge their descriptions together
4. Once the release has finished, edit the release on https://github.com/textileio/js-http-client/releases and make it really nice

So that way https://github.com/textileio/js-http-client/releases is the changelog. This can be seen in practice at https://github.com/textileio/go-textile/releases

**Comment by carsonfarmer** [comment]
While I didn't quite nail the above workflow, we're close. So closing this in favor of adopting the above 'best practice'.

**Comment by balupton** [comment]
Perfect well done
